name: Deploy

on:
  push:
    branches: [master ]
  pull_request:
    branches: [master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v1

      - name: Connect via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: git clone https://github.com/tpofd/common-data-app/ temp &&
                  mv ./temp/backend ./backend &&
                  mv ./temp/frontend ./frontend &&
                  mv ./temp/data/ ./data &&
                  mv ./temp/docker-compose.yml ./docker-compose.yml &&
                  rm -rf ./temp &&
                  docker-compose up --build
