name: Deploy

on:
  push:
    branches: [master ]
  pull_request:
    branches: [master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
                  rm -rf temp &&
                  git clone https://github.com/tpofd/common-data-app/ ./temp &&
                  rsync -a temp/. app &&
                  rm -rf temp &&
                  cd app &&
                  docker-compose up --build -d
